name: build

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'webrtc-sdk commit hash'
        default: ''
        required: true
      configuration:
        description: 'build configuration'
        default: 'release'
        required: true
        type: choice
        options:
          - release
          - debug
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
      - '.dockerignore'
    branches-ignore:
      - daily
    tags:
      - '*'

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  build-apple:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          - apple
          - apple_prefixed
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v5
    - name: Select Xcode 26.6
      run: sudo xcode-select --switch /Applications/Xcode_26.6.app/Contents/Developer
    - name: Build
      id: build
      run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}" "${{ github.event.inputs.configuration || 'release' }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.framework_name }}.xcframework.zip
        path: build/_package/${{ matrix.name }}/${{ steps.build.outputs.framework_name }}.xcframework.zip
